name: ${project.name}
version: ${project.version}
main: ${main.class}
author: ${author}

api-version: 1.20
depend: [ProjectKorra]
description: RPG side-plugin for ProjectKorra core
website: https://projectkorra.com